services:
  - type: web
    name: instaapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1
